import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,1,2],[1,1,1],[1,1,1]])
print(a,b)

print(np.shape(a))
print(np.shape(b))
c=np.add(a,b)
print(c)
d=np.array([10,20,30])
print(np.shape(d))
print(np.add(a,d))
e=np.array([10,20])
print(e)
#print(np.add(d,e))  #wont add 2/3 dimenison
f=np.array([10])
print(f)
print(np.shape(f))
print(np.add(a,f))
print(np.subtract(a,f))
print(np.subtract(b,f))
print(np.subtract(a,b))
print(np.multiply(a,f))
print(np.divide(a,b))
print(np.power(a,b))
print(np.mod(a,b))
print(np.mod(a,3))
print(np.reciprocal(f))
g=np.array([0.5,0.3,0.4])
print(np.reciprocal(g))
complex=np.array([5+6j,10-5j,9+7j])
print(complex)
print(np.real(complex))
print(np.imag(complex))
print(np.conjugate(complex))
print(complex)